DEFAULT_LAYOUT_SCALE: float = 1.0

DEFAULT_COOLING_RATE: float = 0.95
DEFAULT_TEMPERATURE_FRACTION: float = 0.10

MIN_POSITIVE_VALUE: float = 1e-8

K_MIN_FACTOR: float = 0.10
K_MAX_FACTOR: float = 5.00

TEMPERATURE_MIN_FACTOR: float = 0.001
TEMPERATURE_MAX_FACTOR: float = 2.00

COOLING_RATE_MIN: float = 0.80
COOLING_RATE_MAX: float = 0.999

FR_EPSILON: float = 1e-9